### ISSUE TITLE
Performance under the unified setting

### ISSUE THREAD

**Issue by caiyuxuan1120** [DonaldRR/SimpleNet#16]
I try to train the SimpleNet under the unified (multi-class) setup, but the performance is extremely low. I don't know why…maybe someone else has tried to do this?

**Comment by DonaldRR** [comment]
There would be much more normal feature "clusters" when adding more classes. "Splitting" the normal ones from the anomalous ones could be much difficult. 
Also, it adds more challenges to the model when the following cases happen:
1. The feature of background of certain classes is similar to foreground of other classes - The task is essentially modeling normal features of object/texture (i.e. the foreground of image)
2. The feature of defect of certain classes is similar to foreground of other classes - no need to explain

You can also refer to https://github.com/DonaldRR/SimpleNet/issues/9.
