### ISSUE TITLE
How can I show the results like Figure 8 in the paper?

### ISSUE THREAD

**Issue by thanhthanhhp123** [DonaldRR/SimpleNet#17]
After training, I have results. Now how can I show the result like in Figure 8. Please help me!!!

**Comment by DonaldRR** [comment]
Just plot the anomaly map from the output

**Comment by thanhthanhhp123** [comment]
> Just plot the anomaly map from the output

I see the **plot_segmentation_images** function in **utils.py**. Can you help me to use it?
