### ISSUE TITLE
SimpleNet is faster than Patchcore ?

### ISSUE THREAD

**Issue by thianlianben-gs** [DonaldRR/SimpleNet#24]
the paper described as Simplenet is 8* faster than patchcore. 

I have a doubt. Whenever I measure inference time on my gpu, the speed of SimpleNet reach at only 3/4 FPS. But patchcore get reached at 16/17 FPS on my gpu. 
SimpleNet contains four components as mentioned in the paper. Patchcore has 2 components only.

**Comment by code10086web** [comment]
I have same doubt!
