### ISSUE TITLE
bias in projection

### ISSUE THREAD

**Issue by hlr7999** [DonaldRR/SimpleNet#27]
Hi, i have a question about the bias in projection (feature adapter in paper).
The description in the paper is

> The later feature adaptor is essentially a fully connected layer **_without bias_**

However, the code in Projection is
```python
self.layers.add_module(f"{i}fc", 
                                   torch.nn.Linear(_in, _out))
```
Since the default argument of bias is True in torch.nn.Linear,
It this a mistake or the existence of bias is not important ?

**Comment by DonaldRR** [comment]
In my experiments, it can be as simple as without bias, or the bias is not that important.
