### ISSUE TITLE
Getting Issue in running the code

### ISSUE THREAD

**Issue by asadmujtaba** [DonaldRR/SimpleNet#33]
I am a begineer and having some difficulty in running the code. 
Error: Missing argument 'DATA_PATH'. Even though i have written correct datapath in line 1 as described
I have attached the issue with screenshot. please can someone guide?
![Untitled](https://github.com/DonaldRR/SimpleNet/assets/32150927/67d96210-20bd-4672-8339-14bb1101ce25)

**Comment by DonaldRR** [comment]
Notice the error message from your bash: "line 1: /home/mujtaba/CodeTests/SimpleNet-main/MVTec_ad: Is a directory"
