### ISSUE TITLE
The feature about feeding to discriminator

### ISSUE THREAD

**Issue by FFFox-abc** [DonaldRR/SimpleNet#36]
I find in the `_train_discriminator()` function in simplenet.py after the _embed() function, the feature becomes [10368, 1536], It's a two dimensions feature and no batch information, and then use this feature to train the discriminator. But for the output of the discriminator, it's like 10368 positive results and 10368 negetive result?  And no batch information. I got confused. Why they need do those.

**Comment by DonaldRR** [comment]
The features of the batch are flattened(reshape) to 1D here.
