### ISSUE TITLE
not enough values to unpack (expected 3, got 2) for test script

### ISSUE THREAD

**Issue by hurri2000** [DonaldRR/SimpleNet#39]
i_auroc, p_auroc, pro_auroc = SimpleNet.test(dataloaders["training"], dataloaders["testing"], save_segmentation_images)
ValueError: not enough values to unpack (expected 3, got 2)

while in test:
only return two values
return auroc, full_pixel_auroc

**Comment by zckdj** [comment]
我也遇到了同样的问题

**Comment by Abhijeet99999** [comment]
Getting same Error. How to solved it ?

**Comment by DonaldRR** [comment]
The evaluation process is included in "train" method.
