### ISSUE TITLE
ViT's performance is poor

### ISSUE THREAD

**Issue by zhaoyuan1209** [DonaldRR/SimpleNet#4]
I got poor performance(I-AUC 0.723 P-AUC 0.617  ,P-AUROC 0.248) by using VIT_B.  May I ask whether it was originally so bad or there is something wrong with my code

**Comment by roomo7time** [comment]
Vit is not translation equivariant. Thus, anomaly pixel at a position is not similar to the same anomaly at a different position in the feature space. And thus the discriminator does not work.

**Comment by yuhbai** [comment]
how to use vit as backbone
