### ISSUE TITLE
运行run.sh报错   File "main.py", line 35, in <module>     @main.result_callback() TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by lxslxs1** [DonaldRR/SimpleNet#40]
![image](https://github.com/DonaldRR/SimpleNet/assets/59115350/77e876e9-7f10-4f18-9d3c-34e74485d3f5)
我的run.sh文件为：
datapath=./data4/MVTec_ad
datasets=('screw' 'pill' 'capsule' 'carpet' 'grid' 'tile' 'wood' 'zipper' 'cable' 'toothbrush' 'transistor' 'metal_nut' 'bottle' 'hazelnut' 'leather')
dataset_flags=($(for dataset in "${datasets[@]}"; do echo '-d '"${dataset}"; done))

python3 main.py \
--gpu 4 \
--seed 0 \
--log_group simplenet_mvtec \
--log_project MVTecAD_Results \
--results_path results \
--run_name run \
net \
-b wideresnet50 \
-le layer2 \
-le layer3 \
--pretrain_embed_dimension 1536 \
--target_embed_dimension 1536 \
--patchsize 3 \
--meta_epochs 40 \
--embedding_size 256 \
--gan_epochs 4 \
--noise_std 0.015 \
--dsc_hidden 1024 \
--dsc_layers 2 \
--dsc_margin .5 \
--pre_proj 1 \
dataset \
--batch_size 8 \
--resize 329 \
--imagesize 288 "${dataset_flags[@]}" mvtec $datapath

**Comment by anhuiAlice** [comment]
python的版本一定要是3.8，带的那个click是对应的

**Comment by lxslxs1** [comment]
> python的版本一定要是3.8，带的那个click是对应的

感谢！重装环境成功了！
