### ISSUE TITLE
Where to find visulization results ?

### ISSUE THREAD

**Issue by Abhijeet241093** [DonaldRR/SimpleNet#43]
Code is running but it does not return  visualization results for image and segmented mask?

INFO:__main__:Training models (1/1)
Not enough points to compute AUC.                                                                                                                                                   
INFO:__main__:Instance AUROC: 0.998
INFO:__main__:Full Pixel AUROC: 0.923
INFO:__main__:Anomaly Pixel AUROC is None. Skipping logging.
INFO:__main__:instance_auroc: 0.998
INFO:__main__:full_pixel_auroc: 0.923
INFO:__main__:anomaly_pixel_auroc: None
INFO:__main__:

-----

INFO:utils:instance_auroc: 0.998
INFO:utils:full_pixel_auroc: 0.923
/home/radhakrishna/SimpleNet/utils.py:170: RuntimeWarning: Mean of empty slice
  mean_metrics[result_key] = np.nanmean(filtered_results)
INFO:utils:anomaly_pixel_auroc: nan

**Comment by Abhijeet99999** [comment]
Issues is unresolved

**Comment by DonaldRR** [comment]
Pls READ the code.

**Comment by Parkkkkk** [comment]
@Abhijeet241093
Please edit the file path for your check_file in that section.

simplenet.py
389 Line   ->   ckpt_path = os.path.join()
