### ISSUE TITLE
The problem of Feature Adaptor  特征适配器

### ISSUE THREAD

**Issue by Onlydrink** [DonaldRR/SimpleNet#44]
特征适配器这部分可以单独拿出来作为两个数据集特征的适配吗？ 如果可以该怎么实现呢
Can the feature adapter section be separated as an adaptation of the features of the two data sets? And if so, how

![image](https://github.com/DonaldRR/SimpleNet/assets/55441895/eea17edf-a34a-46a5-b59a-1ece0bf993cd)

**Comment by DonaldRR** [comment]
It is dataset-specific by design. Not recommend doing so, but you can try it as experientation.

**Comment by Onlydrink** [comment]
Thank you very much for the author's reply. Does this setting for a specific data set refer to ImageNet data set to MvTecAD?
