### ISSUE TITLE
Is it possible to predict test data without using ground truth ? i

### ISSUE THREAD

**Issue by Abhijeet241093** [DonaldRR/SimpleNet#46]
Hello Sir,
 
Actually, trained model without test data. Then, tested model on test data without ground truth, Howhevere, ... unable to get proper segementation results. 
is it compulsory to include ground truth ?

**Comment by DonaldRR** [comment]
Not sure the problem you mentioned. Testing process can surely go well without ground truth.

**Comment by DonaldRR** [comment]
You may need to edit the Dataset stuff

**Comment by Abhijeet241093** [comment]
Problem is not solved. Question is it possible to train model without ground truth and test data ? and even tried it does not work, bcs your code, always need segmentation during training.
