### ISSUE TITLE
ValueError: Only one class present in y_true. ROC AUC score is not defined in that case.

### ISSUE THREAD

**Issue by FFFox-abc** [DonaldRR/SimpleNet#5]
Hi，
I modified the MVTec dataset root in run.sh, but during the training. I got the following error:
ValueError: Only one class present in y_true. ROC AUC score is not defined in that case.

Is the something wrong in run.sh? I just modified the frist line(MVTec dataset root) in the run.sh file

**Comment by honghuzi** [comment]
> Hi， I modified the MVTec dataset root in run.sh, but during the training. I got the following error: ValueError: Only one class present in y_true. ROC AUC score is not defined in that case.
> 
> Is the something wrong in run.sh? I just modified the frist line(MVTec dataset root) in the run.sh file

same problem here, how did you solve that?

**Comment by FFFox-abc** [comment]
by adding some other type image， if your test only include one class (good or bad), you need add other class in test data

**Comment by 1320414730** [comment]
How to operate specifically, can you give an example

**Comment by 1320414730** [comment]
> by adding some other type image， if your test only include one class (good or bad), you need add other class in test data

How to operate specifically, can you give an example

**Comment by FFFox-abc** [comment]
In your test data, it should include more than one class, like good and bad cases. and you need to specific which one is the good case.







------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年10月12日(星期四) 下午3:41
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [DonaldRR/SimpleNet] ValueError: Only one class present in y_true. ROC AUC score is not defined in that case. (Issue #5)





 
How to operate specifically, can you give an example

**Comment by 1320414730** [comment]
Thank you for your response.&nbsp;
May I ask if the categories are distinguished by a directory structure, such as follows：


----grountruth
&nbsp; &nbsp; &nbsp; ----good
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ----00001.png
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ----00002.png
&nbsp; &nbsp; &nbsp; ----bad
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ----00001.png


----test
&nbsp; &nbsp; &nbsp; ----good
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ----0001.jpg
&nbsp; &nbsp; &nbsp; ----bad
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ----0001.jpg


----train
&nbsp; &nbsp; &nbsp; ----good
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ----0001.jpg


However, it seems that this is not working.




1320414730
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DonaldRR/SimpleNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月19日(星期四) 中午1:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [DonaldRR/SimpleNet] ValueError: Only one class present in y_true. ROC AUC score is not defined in that case. (Issue #5)





 In your test data, it should include more than one class, like good and bad cases. and you need to specific which one is the good case. 
 
 
 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: ***@***.***&amp;gt;;  
 发送时间: 2023年10月12日(星期四) 下午3:41 
 收件人: ***@***.***&amp;gt;;  
 抄送: ***@***.***&amp;gt;; "State ***@***.***&amp;gt;;  
 主题: Re: [DonaldRR/SimpleNet] ValueError: Only one class present in y_true. ROC AUC score is not defined in that case. (Issue #5) 
 
 
 
 
 
   
 How to operate specifically, can you give an example

**Comment by FFFox-abc** [comment]
sorry for the late reply

this is my data structure









------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DonaldRR/SimpleNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月19日(星期四) 下午5:34
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [DonaldRR/SimpleNet] ValueError: Only one class present in y_true. ROC AUC score is not defined in that case. (Issue #5)





 Thank you for your response.&amp;nbsp; 
 May I ask if the categories are distinguished by a directory structure, such as follows： 
 
 
 ----grountruth 
 &amp;nbsp; &amp;nbsp; &amp;nbsp; ----good 
 &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; ----00001.png 
 &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; ----00002.png 
 &amp;nbsp; &amp;nbsp; &amp;nbsp; ----bad 
 &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; ----00001.png 
 
 
 ----test 
 &amp;nbsp; &amp;nbsp; &amp;nbsp; ----good 
 &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; ----0001.jpg 
 &amp;nbsp; &amp;nbsp; &amp;nbsp; ----bad 
 &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; ----0001.jpg 
 
 
 ----train 
 &amp;nbsp; &amp;nbsp; &amp;nbsp; ----good 
 &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; ----0001.jpg 
 
 
 However, it seems that this is not working. 
 
 
 
 
 1320414730 
 ***@***.*** 
 
 
 
 &amp;nbsp; 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "DonaldRR/SimpleNet"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2023年10月19日(星期四) 中午1:18 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [DonaldRR/SimpleNet] ValueError: Only one class present in y_true. ROC AUC score is not defined in that case. (Issue #5) 
 
 
 
 
 
  In your test data, it should include more than one class, like good and bad cases. and you need to specific which one is the good case.  
   
   
   
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人: ***@***.***&amp;amp;gt;;   
  发送时间: 2023年10月12日(星期四) 下午3:41  
  收件人: ***@***.***&amp;amp;gt;;   
  抄送: ***@***.***&amp;amp;gt;; "State ***@***.***&amp;amp;gt;;   
  主题: Re: [DonaldRR/SimpleNet] ValueError: Only one class present in y_true. ROC AUC score is not defined in that case. (Issue #5)  
   
   
   
   
   
     
  How to operate specifically, can you give an example

**Comment by 1320414730** [comment]
thanks，but it seems that your reply has no relevant content，just like the screenshot I sent you. Can you send it to me as an attachment




1320414730
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DonaldRR/SimpleNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月7日(星期二) 上午9:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [DonaldRR/SimpleNet] ValueError: Only one class present in y_true. ROC AUC score is not defined in that case. (Issue #5)





 sorry for the late reply 
 
 this is my data structure 
 
 
 
 
 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "DonaldRR/SimpleNet"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2023年10月19日(星期四) 下午5:34 
 ***@***.***&amp;gt;; 
 ***@***.***&amp;gt;;"State ***@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [DonaldRR/SimpleNet] ValueError: Only one class present in y_true. ROC AUC score is not defined in that case. (Issue #5) 
 
 
 
 
 
  Thank you for your response.&amp;amp;nbsp;  
  May I ask if the categories are distinguished by a directory structure, such as follows：  
   
   
  ----grountruth  
  &amp;amp;nbsp; &amp;amp;nbsp; &amp;amp;nbsp; ----good  
  &amp;amp;nbsp; &amp;amp;nbsp; &amp;amp;nbsp; &amp;amp;nbsp; &amp;amp;nbsp; &amp;amp;nbsp; ----00001.png  
  &amp;amp;nbsp; &amp;amp;nbsp; &amp;amp;nbsp; &amp;amp;nbsp; &amp;amp;nbsp; &amp;amp;nbsp; ----00002.png  
  &amp;amp;nbsp; &amp;amp;nbsp; &amp;amp;nbsp; ----bad  
  &amp;amp;nbsp; &amp;amp;nbsp; &amp;amp;nbsp; &amp;amp;nbsp; &amp;amp;nbsp; &amp;amp;nbsp; ----00001.png  
   
   
  ----test  
  &amp;amp;nbsp; &amp;amp;nbsp; &amp;amp;nbsp; ----good  
  &amp;amp;nbsp; &amp;amp;nbsp; &amp;amp;nbsp; &amp;amp;nbsp; &amp;amp;nbsp; &amp;amp;nbsp; ----0001.jpg  
  &amp;amp;nbsp; &amp;amp;nbsp; &amp;amp;nbsp; ----bad  
  &amp;amp;nbsp; &amp;amp;nbsp; &amp;amp;nbsp; &amp;amp;nbsp; &amp;amp;nbsp; &amp;amp;nbsp; ----0001.jpg  
   
   
  ----train  
  &amp;amp;nbsp; &amp;amp;nbsp; &amp;amp;nbsp; ----good  
  &amp;amp;nbsp; &amp;amp;nbsp; &amp;amp;nbsp; &amp;amp;nbsp; &amp;amp;nbsp; &amp;amp;nbsp; ----0001.jpg  
   
   
  However, it seems that this is not working.  
   
   
   
   
  1320414730  
  ***@***.***  
   
   
   
  &amp;amp;nbsp;  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:                                                                                                                        "DonaldRR/SimpleNet"                                                                                    ***@***.***&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2023年10月19日(星期四) 中午1:18  
  ***@***.***&amp;amp;gt;;  
  ***@***.******@***.***&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [DonaldRR/SimpleNet] ValueError: Only one class present in y_true. ROC AUC score is not defined in that case. (Issue #5)  
   
   
   
   
   
   In your test data, it should include more than one class, like good and bad cases. and you need to specific which one is the good case.   
     
     
     
     
     
     
     
   ------------------&amp;amp;amp;nbsp;原始邮件&amp;amp;amp;nbsp;------------------   
   发件人: ***@***.***&amp;amp;amp;gt;;    
   发送时间: 2023年10月12日(星期四) 下午3:41   
   收件人: ***@***.***&amp;amp;amp;gt;;    
   抄送: ***@***.***&amp;amp;amp;gt;; "State ***@***.***&amp;amp;amp;gt;;    
   主题: Re: [DonaldRR/SimpleNet] ValueError: Only one class present in y_true. ROC AUC score is not defined in that case. (Issue #5)   
     
     
     
     
     
       
   How to operate specifically, can you give an example

**Comment by boxbox2** [comment]
> 谢谢，不过你的回复好像没有相关内容，和我发的截图一样，能不能以附件形式发给我1320414730 ***@***.***  
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: “DonaldRR/SimpleNet “***@***.***>;发送时间:2023年11月7日(星期二) 上午9:07 ***@***.***>; ***@***.******@***.***>;主题: 回复：[DonaldRR/SimpleNet] ValueError: y_true 中仅存在一个类。在这种情况下，ROC AUC 分数未定义。 （问题#5）抱歉回复晚了，这是我的数据结构
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: “DonaldRR/SimpleNet”***@***.***&gt;；发送时间:2023年10月19日(星期四)下午5:34 ***@***.***&gt;; ***@***.***&gt;;"状态 ***@***.***&gt;; 主题:&nbsp;Re: [DonaldRR/SimpleNet] ValueError: Only y_true 中存在一个类。这种情况下 ROC AUC 分数没有定义。（问题#5） 感谢您的回复。请问类别是否可以用目录结构来区分，比如如下：
> ----grountruth &amp;nbsp; &amp;nbsp; &amp;nbsp; ----好 &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; ----00001.png &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; ----00002.png &amp;nbsp; &amp;nbsp; &amp;nbsp; ----坏 &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; ----00001.png
> ----测试 &amp;nbsp; &amp;nbsp; &amp;nbsp; ----好 &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; ----0001.jpg &amp;nbsp; &amp;nbsp; &amp;nbsp; ----坏 &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; ----0001.jpg
> ----train &amp;nbsp; &amp;nbsp; &amp;nbsp; ----good &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; ----0001.jpg 但是，这似乎不起作用。 1320414730 ***@***.*** &amp;nbsp;
> ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 发件人: "DonaldRR/SimpleNet" ***@***.***&amp;gt;; 发送时间:&amp;nbsp;2023年10月19日(星期四) 中午1:18 ***@***.***&amp;gt;; ***@***.******@***.***&amp;gt;; 主题:&amp;nbsp;回复：[DonaldRR/SimpleNet] ValueError: y_true 中只有一个类。该案例中未定义 ROC AUC 分数。(问题#5 ) 在您的测试数据中，它应该包含多个类，例如好案例和坏案例。并且您需要具体说明哪一个是好案例。
> ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;----------- ---- 发件人: ***@***.***&amp;amp;gt;;发送时间： 2023年10月12日(星期四) 下午3:41 收件人： ***@***.***&amp;amp;gt;;抄送：***@***.***&amp;amp;gt;; “状态 ***@***.***&amp;amp;gt;; 主题：回复：[DonaldRR/SimpleNet] ValueError：y_true 中仅存在一个类。在这种情况下，ROC AUC 分数未定义。 （问题#5）具体怎么操作，能举个例子吗 — 直接回复这封邮件，在 GitHub 上查看，或者退订。您收到这封邮件是因为您修改了打开/关闭状态。消息 ID：***@ ***.***&amp;amp;gt; — 直接回复此电子邮件、在 GitHub 上查看或取消订阅。您收到此邮件是因为您发表了评论。消息 ID：***@***.* **&amp;gt; — 直接回复此电子邮件、在 GitHub 上查看或取消订阅。您收到此邮件是因为您修改了打开/关闭状态。消息 ID：***@***.*** &gt; — 直接回复此电子邮件、在 GitHub 上查看或取消订阅。您收到此邮件是因为您发表了评论。消息 ID：***@***.***>

hi,我也遇到这个问题了，请问你解决了吗？

**Comment by boxbox2** [comment]
> 通过添加一些其他类型的图像，如果你的测试只包括一个类（好或坏），你需要在测试数据中添加其他类

hi，
![image](https://github.com/DonaldRR/SimpleNet/assets/56194614/a98053b9-a242-4ac4-978a-84e67c7282cc)
这是我的数据目录，请问您是怎么解决ValueError: Only one class present in y_true. ROC AUC score is not defined in that case这个问题的
