### ISSUE TITLE
缺陷检测交流微信群，互相交流学习进步

### ISSUE THREAD

**Issue by RuojiWang** [DonaldRR/SimpleNet#52]
缺陷检测交流微信群，互相交流学习进步

![20240108092627](https://github.com/DonaldRR/SimpleNet/assets/14054362/895d9d55-ac94-4deb-a642-2405602947a3)

**Comment by RuojiWang** [comment]
![微信图片_20240115152819](https://github.com/DonaldRR/SimpleNet/assets/14054362/f7a6a250-e91b-472e-a6d7-23ee11ad9044)

**Comment by RuojiWang** [comment]
![微信图片_20240122140446](https://github.com/DonaldRR/SimpleNet/assets/14054362/7e0d0a7b-b336-4ef9-84d1-096eec98a999)

**Comment by RuojiWang** [comment]
![微信图片_20240129140511](https://github.com/DonaldRR/SimpleNet/assets/14054362/850288fb-d758-4a24-bc15-d3520ea11a13)

**Comment by RuojiWang** [comment]
![微信图片_20240206092951](https://github.com/DonaldRR/SimpleNet/assets/14054362/c732b1e1-5c62-45d9-ac67-185bfc0075c4)

**Comment by RuojiWang** [comment]
![微信图片_20240219092628](https://github.com/DonaldRR/SimpleNet/assets/14054362/2519f2a1-ebd9-4be6-9a78-8b14a0aa5aca)

**Comment by RuojiWang** [comment]
![微信图片_20240227095422](https://github.com/DonaldRR/SimpleNet/assets/14054362/3c33987d-a9ba-493d-b1de-c1397b9365e4)

**Comment by kimsax** [comment]
> ![微信图片_20240227095422](https://private-user-images.githubusercontent.com/14054362/308010626-3c33987d-a9ba-493d-b1de-c1397b9365e4.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0NDk0NzQsIm5iZiI6MTcxMjQ0OTE3NCwicGF0aCI6Ii8xNDA1NDM2Mi8zMDgwMTA2MjYtM2MzMzk4N2QtYTliYS00OTNkLWIxZGUtYzEzOTdiOTM2NWU0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDAwMTkzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4MDEyNGY0MGFkM2U2ZTQ2ZjVjOTQ5MjdmOWJhZGY4MmEzZjFhNWM2NzkyMzBlOTUyYTMzNzY3MmVjYTZmNjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.B14JEHZT8CG2dU71HGdC3_9Toe8bqqWegT6eRY6vIYw)

新二维码

**Comment by kimsax** [comment]
> ![微信图片_20240227095422](https://private-user-images.githubusercontent.com/14054362/308010626-3c33987d-a9ba-493d-b1de-c1397b9365e4.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0NTE2MDQsIm5iZiI6MTcxMjQ1MTMwNCwicGF0aCI6Ii8xNDA1NDM2Mi8zMDgwMTA2MjYtM2MzMzk4N2QtYTliYS00OTNkLWIxZGUtYzEzOTdiOTM2NWU0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDAwNTUwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhM2I1ODhlZmQzODc1NTJhYzJmMWI3ZjdiYzYxZDdmZjhhNTFlN2VkMmVhZTY2ZmIyMGEzOWQ3NGNhNzdlM2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mvAT_EVHXBqCQVM8xegc7UmVCwxuXGwYJMcWRjyYo_s)

你好，有新的群二维码吗

**Comment by RuojiWang** [comment]
好的，我重新发一份

![微信图片_20240407121310](https://github.com/DonaldRR/SimpleNet/assets/14054362/03f3f1d0-7cd9-418d-a8b9-168b49eebacd)

**Comment by happyrenxiaozhao** [comment]
@RuojiWang 又失效了，马上重新发一下

**Comment by RuojiWang** [comment]
> @RuojiWang 又失效了，马上重新发一下

![微信图片_20240527123250](https://github.com/DonaldRR/SimpleNet/assets/14054362/97d99bd7-34be-4ec6-ac9f-ab62578c26bb)

**Comment by Hxh-sota** [comment]
可以再发个二维码吗 我也想加入

**Comment by ample52004** [comment]
可以麻烦再发个二维码吗 我也想加入

**Comment by SwunChao** [comment]
可以再发一次吗

**Comment by hardwd** [comment]
可以再发一次吗？
