### ISSUE TITLE
code erro for low auroc  when test

### ISSUE THREAD

**Issue by wu33learn** [DonaldRR/SimpleNet#53]
simplenet.py   line 291  
ckpt_path = os.path.join(self.ckpt_dir, "models.ckpt")
change to 
ckpt_path = os.path.join(self.ckpt_dir, "ckpt.pth")

why not use "anomaly_pixel_auroc": pro_auroc when test ?

**Comment by wu33learn** [comment]
@DonaldRR

**Comment by lxslxs1** [comment]
这一段代码简直灾难 错得离谱
