### ISSUE TITLE
How to make a simple prediction on a single image after training?

### ISSUE THREAD

**Issue by felipebattist** [DonaldRR/SimpleNet#56]
I have trained a model. The code saves the .pth file in a directory. But I am having trouble trying to simply load the model and predict a single image. The code only saves the Discriminator.

**Comment by felipebattist** [comment]
I achieved single-image predictions by instantiating an instance of the simplenet class. Subsequently, I loaded the Discriminator from the saved .pth file and assigned it to the simplenet instance. Following this, I applied the necessary torch transformations to the image and called the simplenet._predict function to obtain the score for the image.

**Comment by felipebattist** [comment]
I achieved single-image predictions by instantiating an instance of the simplenet class. Subsequently, I loaded the Discriminator from the saved .pth file and assigned it to the simplenet instance. Following this, I applied the necessary torch transformations to the image and called the simplenet._predict function to obtain the score for the image.

**Comment by mericgeren** [comment]
Hello @felipebattist ,

I am trying to do a similar thing, could you explain how did you turn your image into something like `test_data` please?

**Comment by boxbox2** [comment]
Hi, can you show me your code? I also encountered this problem

**Comment by Poonwai** [comment]
Hi, can you show me your code? I also encountered this problem

**Comment by Poonwai** [comment]
Hi, can you show me your code? I also encountered this problem
